-- Status AGUARDANDO_LANCAMENTO nos recebíveis (ciclos encerrados no pátio, antes do financeiro lançar).
--
-- 1) Se a coluna `receivables.status` tiver CHECK ou ENUM que só permita EM_ABERTO e PAGO,
--    ajuste no Supabase (SQL Editor) conforme o nome real da constraint:
--
--    Exemplo (o nome da constraint pode ser outro — veja em information_schema ou no painel Table Editor):
--    -- ALTER TABLE receivables DROP CONSTRAINT IF EXISTS receivables_status_check;
--    -- ALTER TABLE receivables ADD CONSTRAINT receivables_status_check
--    --   CHECK (status IN ('EM_ABERTO', 'PAGO', 'AGUARDANDO_LANCAMENTO'));
--
-- 2) Opcional: migrar na base ciclos EM_ABERTO com período já fechado → AGUARDANDO_LANCAMENTO
--    (ficheiro dedicado: receivables_migrar_em_aberto_com_fim_para_aguardando.sql).
--
-- A interface também trata estes registos em «Aguardando lançamento» sem esse UPDATE.
--
-- 3) Sincronizar aprovação «Ir para contas a receber» entre dispositivos:
--    receivables_financeiro_aprovado_contas.sql
